CREATE TABLE "BOOK" (
  "ISBN" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TITLE" TEXT NOT NULL,
  "EDITION" TEXT NOT NULL,
  "PUBLICATION" DATE NOT NULL
);

CREATE TABLE "COPY" (
  "ID" INTEGER NOT NULL,
  "ACQUIRED" DATE NOT NULL,
  "RETIRED" DATE,
  "ISBN" INTEGER NOT NULL REFERENCES "BOOK" ("ISBN") ON DELETE CASCADE,
  PRIMARY KEY ("ID", "ISBN")
);

CREATE INDEX "idx_copy__isbn" ON "COPY" ("ISBN");

CREATE TABLE "PERSON" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "NAME" TEXT NOT NULL,
  "ADDRESS" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL,
  "PHONE_NUMBER" TEXT NOT NULL
);

CREATE TABLE "AUTHOR" (
  "PERSON_ID" INTEGER NOT NULL PRIMARY KEY REFERENCES "PERSON" ("ID")
);

CREATE TABLE "AUTHOR_BOOK" (
  "author" INTEGER NOT NULL REFERENCES "AUTHOR" ("PERSON_ID"),
  "book" INTEGER NOT NULL REFERENCES "BOOK" ("ISBN"),
  PRIMARY KEY ("author", "book")
);

CREATE INDEX "idx_author_book" ON "AUTHOR_BOOK" ("book");

CREATE TABLE "MEMBER" (
  "PERSON_ID" INTEGER NOT NULL PRIMARY KEY REFERENCES "PERSON" ("ID"),
  "JOINED" DATE NOT NULL,
  "TERMINATED" DATE
);

CREATE TABLE "STAFF" (
  "PERSON_ID" INTEGER NOT NULL PRIMARY KEY REFERENCES "PERSON" ("ID"),
  "JOINED" DATE NOT NULL,
  "TERMINATED" DATE,
  "ROLE" TEXT NOT NULL
);

CREATE TABLE "LOAN" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "BORROW_DATE" DATETIME NOT NULL,
  "DUE_DATE" DATETIME NOT NULL,
  "RETURN_DATE" DATETIME,
  "COPY_ID_ID" INTEGER NOT NULL,
  "COPY_ID_ISBN" INTEGER NOT NULL,
  "ISSUER_ID" INTEGER NOT NULL REFERENCES "STAFF" ("PERSON_ID") ON DELETE CASCADE,
  "MEMBER_ID" INTEGER NOT NULL REFERENCES "MEMBER" ("PERSON_ID") ON DELETE CASCADE,
  FOREIGN KEY ("COPY_ID_ID", "COPY_ID_ISBN") REFERENCES "COPY" ("ID", "ISBN") ON DELETE CASCADE
);

CREATE INDEX "idx_loan__copy_id_id_copy_id_isbn" ON "LOAN" ("COPY_ID_ID", "COPY_ID_ISBN");

CREATE INDEX "idx_loan__issuer_id" ON "LOAN" ("ISSUER_ID");

CREATE INDEX "idx_loan__member_id" ON "LOAN" ("MEMBER_ID")